changelog:
  exclude:
    labels:
      - exclude from release notes
  categories:
    - title: Breaking Changes
      labels:
        - BREAKING
    - title: New Features
      labels:
        - new feature
    - title: Improvements
      labels:
        - improvement
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - maintenance
    - title: Other
      labels:
        - "*"
