name: Publish documentation

on:
  workflow_call:
  # Allow updating docs without releasing a new version by pushing to `update-docs` branch.
  push:
    branches:
      - update-docs

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        working-directory: docs
      - run: npm run build
        working-directory: docs
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/src/.vuepress/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
