name: Publish library

on:
  release:
    types:
      - released

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml

  publish:
    name: Publish to NPM
    needs:
      - test
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org/
      - name: Copy root README.md to library
        run: cp README.md lib/README.md
      - run: npm ci
        working-directory: lib
      - run: npm run build
        working-directory: lib
      - run: npm publish --access public
        working-directory: lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    name: Publish docs
    needs:
      - publish
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/publish_docs.yaml
