name: Publish library

on:
  release:
    types:
      - released

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml

  publish:
    name: Publish to NPM
    needs:
      - test
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: lib
      - run: npm run build
        working-directory: lib
      - run: npm publish --access public
        working-directory: lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    name: Publish docs
    needs:
      - publish
    uses: ./.github/workflows/publish_docs.yaml
