name: Run tests

on:
  push:
  workflow_call:

jobs:
  lint-lib:
    name: Lint (library)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint

  unit-test-lib:
    name: Run unit tests (library)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  annotate:
    name: Code comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joonashak/comment-annotator@v1
