name: Run tests

on:
  workflow_call:

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run check-formatting

  lint-lib:
    name: Lint (library)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint

  lint-dev:
    name: Lint (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint

  unit-test-lib:
    name: Run unit tests (library)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
